name: release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/bump@master
        with:
          github_token: ${{ secrets.GP_TOKEN }}
          unrelated: true
          branch: main

  docs:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: tool3/docsify-action@master
        with:
          github_token: ${{ secrets.GP_TOKEN }}
          branch: main
